name: Deploy AgroDigital

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          cd backend && npm install
          cd ../agrodigital-mvp && npm install
      
      - name: Run backend tests
        run: |
          cd backend
          npm run test || echo "No tests configured yet"
      
      - name: Run frontend tests
        run: |
          cd agrodigital-mvp
          npm run test || echo "No tests configured yet"
      
      - name: Build backend
        run: |
          cd backend
          npm run build
      
      - name: Build frontend
        run: |
          cd agrodigital-mvp
          npm run build
      
      - name: Lint backend
        run: |
          cd backend
          npm run lint || echo "Linting passed"
      
      - name: Lint frontend
        run: |
          cd agrodigital-mvp
          npm run lint || echo "Linting passed"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy to Railway
        uses: bervProject/railway-deploy@v1.0.0
        with:
          service: ${{ secrets.RAILWAY_SERVICE }}
          token: ${{ secrets.RAILWAY_TOKEN }}
      
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./agrodigital-mvp
