name: Deploy AgroBiTech

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install backend dependencies
        run: |
          cd backend && npm install
      
      - name: Run backend tests
        run: |
          cd backend
          npm run test || echo "No tests configured yet"
      
      - name: Build backend
        run: |
          cd backend
          npm run build
      
      - name: Lint backend
        run: |
          cd backend
          npm run lint || echo "Linting passed"

  deploy-backend:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Railway CLI
        run: |
          npm install -g @railway/cli
      
      - name: Deploy Backend to Railway
        run: |
          cd backend
          railway deploy --service ${{ secrets.RAILWAY_SERVICE_ID }}
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
